name: radwo
title: radwo - personal blog about ruby and stuff
description: Radosław Woźniak's personal blog
theme: jekyll-theme-cayman
markdown: redcarpet
highlighter: 'pygments'
safe: true
lsi: false
